# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import collection_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  serialized_pb='\n\ntest.proto\x1a\x10\x63ollection.proto\"3\n\x0cTestResource\x12#\n\ncollection\x18\x01 \x01(\x0b\x32\x0f.TestCollection\"\xd1\x01\n\x0eTestCollection\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04href\x18\x02 \x01(\t\x12\x1f\n\x05links\x18\x03 \x03(\x0b\x32\x10.collection.Link\x12\x18\n\x05items\x18\x04 \x03(\x0b\x32\t.TestItem\x12\"\n\x07queries\x18\x05 \x03(\x0b\x32\x11.collection.Query\x12\x1f\n\x08template\x18\x06 \x01(\x0b\x32\r.TestTemplate\x12 \n\x05\x65rror\x18\x07 \x01(\x0b\x32\x11.collection.Error\"+\n\x0cTestTemplate\x12\x1b\n\x02pb\x18\x01 \x01(\x0b\x32\x0f.TestTemplatePB\",\n\x0eTestTemplatePB\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"L\n\x08TestItem\x12\x0c\n\x04href\x18\x01 \x01(\t\x12\x11\n\x02pb\x18\x02 \x01(\x0b\x32\x05.Test\x12\x1f\n\x05links\x18\x03 \x03(\x0b\x32\x10.collection.Link\"\"\n\x04Test\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t')




_TESTRESOURCE = _descriptor.Descriptor(
  name='TestResource',
  full_name='TestResource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collection', full_name='TestResource.collection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=83,
)


_TESTCOLLECTION = _descriptor.Descriptor(
  name='TestCollection',
  full_name='TestCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='TestCollection.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='href', full_name='TestCollection.href', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='TestCollection.links', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='TestCollection.items', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queries', full_name='TestCollection.queries', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='template', full_name='TestCollection.template', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='TestCollection.error', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=295,
)


_TESTTEMPLATE = _descriptor.Descriptor(
  name='TestTemplate',
  full_name='TestTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pb', full_name='TestTemplate.pb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=297,
  serialized_end=340,
)


_TESTTEMPLATEPB = _descriptor.Descriptor(
  name='TestTemplatePB',
  full_name='TestTemplatePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TestTemplatePB.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='TestTemplatePB.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=342,
  serialized_end=386,
)


_TESTITEM = _descriptor.Descriptor(
  name='TestItem',
  full_name='TestItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='href', full_name='TestItem.href', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pb', full_name='TestItem.pb', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='TestItem.links', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=464,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Test.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='Test.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=466,
  serialized_end=500,
)

_TESTRESOURCE.fields_by_name['collection'].message_type = _TESTCOLLECTION
_TESTCOLLECTION.fields_by_name['links'].message_type = collection_pb2._LINK
_TESTCOLLECTION.fields_by_name['items'].message_type = _TESTITEM
_TESTCOLLECTION.fields_by_name['queries'].message_type = collection_pb2._QUERY
_TESTCOLLECTION.fields_by_name['template'].message_type = _TESTTEMPLATE
_TESTCOLLECTION.fields_by_name['error'].message_type = collection_pb2._ERROR
_TESTTEMPLATE.fields_by_name['pb'].message_type = _TESTTEMPLATEPB
_TESTITEM.fields_by_name['pb'].message_type = _TEST
_TESTITEM.fields_by_name['links'].message_type = collection_pb2._LINK
DESCRIPTOR.message_types_by_name['TestResource'] = _TESTRESOURCE
DESCRIPTOR.message_types_by_name['TestCollection'] = _TESTCOLLECTION
DESCRIPTOR.message_types_by_name['TestTemplate'] = _TESTTEMPLATE
DESCRIPTOR.message_types_by_name['TestTemplatePB'] = _TESTTEMPLATEPB
DESCRIPTOR.message_types_by_name['TestItem'] = _TESTITEM
DESCRIPTOR.message_types_by_name['Test'] = _TEST

class TestResource(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTRESOURCE

  # @@protoc_insertion_point(class_scope:TestResource)

class TestCollection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTCOLLECTION

  # @@protoc_insertion_point(class_scope:TestCollection)

class TestTemplate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTTEMPLATE

  # @@protoc_insertion_point(class_scope:TestTemplate)

class TestTemplatePB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTTEMPLATEPB

  # @@protoc_insertion_point(class_scope:TestTemplatePB)

class TestItem(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTITEM

  # @@protoc_insertion_point(class_scope:TestItem)

class Test(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEST

  # @@protoc_insertion_point(class_scope:Test)


# @@protoc_insertion_point(module_scope)
